### PR TITLE
Test function

### PR DESCRIPTION
**Pull request by Purinut12**
Combine echo controller and service with peer

### CODE REVIEW

**Review by UtopiaBeam — CHANGES_REQUESTED** [review]
Please update your code from master branch.

**Comment by Purinut12** [comment]
I already pulled the latest commit from branch master.

**Comment by Purinut12** [comment]
> Please update your code from master branch.

I already pulled the latest commit from branch master.

**Review by UtopiaBeam — COMMENTED** [review]
Did you try to run in docker?

**Comment by Purinut12** [comment]
No, not yet.

**Comment by UtopiaBeam** [comment]
> No, not yet.

I have feeling that it's gonna break. Maybe we should try to run it first.

**Comment by UtopiaBeam** [comment]
@Purinut12 Never mind, I think we should merge this first.

**Review by UtopiaBeam — APPROVED** [review]

**Pull request merged**
